# DO NOT EDIT:
# This file is generated by tools/export_map_projection.py.
from dcs.terrain.projections import TransverseMercator

PARAMETERS = TransverseMercator(
    central_meridian=63,
    false_easting=-300149.9999999864,
    false_northing=-3759657.000000049,
    scale_factor=0.9996,
)
